dist: xenial

language: python

cache: pip

python:
    - "3.6"
    - "3.7"

install:
    - pip install flit
    - flit install

script:
    - bash scripts/test.sh

after_script:
    - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: bash scripts/trigger-docker.sh
  on:
    branch: master
