site_name: FastAPI
site_description: FastAPI framework, high performance, easy to learn, fast to code, ready for production

theme:
    name: 'material'
    palette:
      primary: 'teal'
      accent: 'amber'
    logo: 'img/icon-white.svg'
    favicon: 'img/favicon.png'

repo_name: tiangolo/fastapi
repo_url: https://github.com/tiangolo/fastapi
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Features: 'features.md'
    - Tutorial:
        - Tutorial Intro: 'tutorial/intro.md'
        - First Steps: 'tutorial/first-steps.md'
        - Path Parameters: 'tutorial/path-params.md'
        - Query Parameters: 'tutorial/query-params.md'
        - Request Body: 'tutorial/body.md'
    - Concurrency and async / await: 'async.md'
    - Deployment: 'deployment.md'
    

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
