name: Notify Translations

on:
  pull_request_target:
    types:
      - labeled

jobs:
  notify-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Allow debugging with tmate
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
      - uses: ./.github/actions/notify-translations
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
