name: Preview Docs
on:
  workflow_run:
    workflows:
      - Build Docs
    types:
      - completed

jobs:
  preview-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clean site
        run: |
          rm -rf ./site
          mkdir ./site
      - name: Download Artifact Docs
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          github_token: ${{ secrets.FASTAPI_PREVIEW_DOCS_DOWNLOAD_ARTIFACTS }}
          workflow: build-docs.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: docs-zip
          path: ./site/
      - name: Unzip docs
        run: |
          cd ./site
          unzip docs.zip
          rm -f docs.zip
      - name: Deploy to Netlify
        id: netlify
        uses: nwtgck/actions-netlify@v2.0.0
        with:
          publish-dir: './site'
          production-deploy: false
          github-token: ${{ secrets.FASTAPI_PREVIEW_DOCS_NETLIFY }}
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Comment Deploy
        uses: ./.github/actions/comment-docs-preview-in-pr
        with:
          token: ${{ secrets.FASTAPI_PREVIEW_DOCS_COMMENT_DEPLOY }}
          deploy_url: "${{ steps.netlify.outputs.deploy-url }}"
